# Generated by Django 5.2.1 on 2025-05-20 13:14

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=15)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='ticker')),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=30)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
                'db_table': 'coin',
                'ordering': ['-market_cap'],
            },
        ),
        migrations.CreateModel(
            name='CoinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=50)),
                ('coin_name', models.CharField(max_length=50)),
                ('coin_ticker', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=30)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Coins History',
                'db_table': 'coin_history',
                'ordering': ['-date'],
                'unique_together': {('coin_id', 'date')},
            },
        ),
    ]
