# Generated by Django 5.2.1 on 2025-05-17 16:01

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='ticker')),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=30)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
            },
        ),
    ]
