# Generated by Django 5.2.1 on 2025-05-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['-market_cap'], 'verbose_name': 'Coin', 'verbose_name_plural': 'Coins'},
        ),
        migrations.AlterField(
            model_name='coin',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
