# Generated by Django 5.2.1 on 2025-05-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coin_options_alter_coin_last_updated'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coin',
            table='coin',
        ),
    ]
