# Generated by Django 5.2.1 on 2025-05-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_coin_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
