# Generated by Django 5.2.1 on 2025-05-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_coin_id_alter_coin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='ticker',
            field=models.CharField(max_length=15),
        ),
    ]
